version: '0.3'

services:
  web:
    build: .
    depends_on:
      - mysql
    container_name: serverApacheMavrylArts
    restart: unless-stopped
    ports:
      - "8851:80"
    volumes:
      - ./php/public:/var/www/html
    environment:
      - ALLOW_OVERRIDE=true
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=mavrylArts
  mysql:
    image: mariadb
    container_name: serverMySQLMavrylArts
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=root
    ports:
      - "3851:3306"
  phpmyadmin:
    image: phpmyadmin
    container_name: serverPHPMyAdminMavrylArts
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
    ports:
      - "7851:80"